[package]
name = "core-usecase"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
core-model = { path = "../core-model" }
core-ports = { path = "../core-ports" }
async-trait = "0.1"

